# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: thingtest  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: thingtest-api  # Replace with the name of the image you want to publish

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
