trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - refs/tags/*

jobs:
  - template: cicd/templates/build-component.job.yml
    parameters:
      componentName: Backend
      subPath: packaged/backend
      stepsTemplate: packages/backend/build.yml

  - template: cicd/templates/build-component.job.yml
    parameters:
      componentName: Studio
      subPath: packages/studio
      stepsTemplate: packages/studio/build.yml