steps:
  - bash: |
      docker build . -t simstore-api:$(git rev-list -1 HEAD)
    workingDirectory: packages/backend/ThingTest.Api
    displayName: Build Docker image
    condition: and(succeeded(), eq(variables.updated, 'true'))